spring:
  application:
    name: 'Test Data Service'
    description: 'Test Data Service Documentation'

server:
  servlet:
    context-path: /
  port: 8065
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain

logging:
  pattern:
    console: "{\"time\": \"%d{yyyy-MM-dd'T'HH:mm:ss}Z\", \"level\": \"%p\", \"agent-name\": \"%X{x-agentname}\", \"correlation-id\": \"%X{x-correlationid}\", \"executor-user\": \"%X{x-executor-user}\", \"remote-host\": \"%X{x-remote-host}\", \"request-path\":\"%X{Request-Path}\", \"user-agent\":\"%X{User-Agent}\", \"source\":\"%logger{63}:%L\", \"message\": \"%replace(%m%wEx{10}){'[\r\n]+', '\n'}%nopex\"}%n"
  level:
    com.derinbay: INFO
